when:
  - event: push
    branch: main

labels:
  platform: darwin/arm64

steps:
  - name: notify-start
    image: bash
    commands:
      - curl -s -X POST "http://192.168.31.215:8095/message?token=A6vmGBx46fXa5Iv" -F "title=WoodpeckerCI" -F "message=WoodpeckerCI - Pipeline Staging iniciada" -F "priority=5"

  - name: testar-codigo
    image: bash
    commands:
      - echo "📦 Instalando dependências..."
      - bun install
      - echo "🧹 Verificando Arquitetura (FSD) e Linter..."
      - bun run lint
      - echo "🔍 Verificando tipagem do App..."
      - bunx tsc --noEmit
      - echo "🔍 Verificando tipagem dos Scripts..."
      - bunx tsc --project scripts/tsconfig.json --noEmit
      - echo "🧪 Executando a suíte de testes..."
      - bun run test

  - name: deploy-ota-staging
    image: bash
    environment:
      EXPO_PUBLIC_API_URL:
        from_secret: api_url_staging
      EXPO_PUBLIC_APP_ENV: "staging"
      APP_ENV: staging
      EXPO_TOKEN:
        from_secret: expo_token
      CI: "true"
      EAS_NO_VCS: "1"
    commands:
      - |
        echo "🚀 Empacotando e enviando atualização OTA para Staging..."
        bunx eas-cli update --branch staging --message "Deploy via CI - Commit: ${CI_COMMIT_SHA}" --non-interactive

  - name: notify-success
    image: bash
    when:
      status: [ success ]
    commands:
      - curl -s -X POST "http://192.168.31.215:8095/message?token=A6vmGBx46fXa5Iv" -F "title=WoodpeckerCI" -F "message=WoodpeckerCI - Pipeline Staging finalizada com sucesso" -F "priority=5"

  - name: notify-error
    image: bash
    when:
      status: [ failure ]
    commands:
      - curl -s -X POST "http://192.168.31.215:8095/message?token=A6vmGBx46fXa5Iv" -F "title=WoodpeckerCI" -F "message=WoodpeckerCI - Falha na Pipeline Staging!" -F "priority=8"