when:
  - event: push
    branch: main

# Essa etiqueta garante que o Mac M1 nunca vai tocar nessa pipeline!
labels:
  platform: linux/arm64

clone:
  git:
    image: woodpeckerci/plugin-git
    extra_hosts:
      - "gitea.brunnoserver.duckdns.org:192.168.31.215"

steps:
  - name: testar-codigo
    image: oven/bun:latest
    commands:
      - echo "📦 Instalando dependências..."
      - bun install
      - echo "🔍 Verificando tipagem do App..."
      - bunx tsc --noEmit
      - echo "🔍 Verificando tipagem dos Scripts..."
      - bunx tsc --project scripts/tsconfig.json --noEmit

  - name: deploy-ota-staging
    image: oven/bun:latest
    environment:
      APP_ENV: staging
      EXPO_TOKEN:
        from_secret: expo_token
      CI: "true" 
    commands:
      - |
        echo "🚀 Empacotando e enviando atualização OTA para Staging..."
        # Usamos o Hash do commit para garantir uma string limpa e rastreável
        bunx eas-cli update --branch staging --message "Deploy via CI - Commit: ${CI_COMMIT_SHA}" --non-interactive